
const CONFIG=window.NAVIGAM_CONFIG;
// Independent client configuration; shared UI and behavior.
const LOCALES=['he','en','ru','ar'];
let LOCALE=CONFIG.client.language;
const storageKey=k=>'navigam:'+CONFIG.id+':'+k;
try{const raw=localStorage.getItem(storageKey('language'));let saved;try{saved=JSON.parse(raw)}catch{saved=raw}if(LOCALES.includes(saved))LOCALE=saved}catch(e){}
function loc(v){if(v&&typeof v==='object'&&!Array.isArray(v))return v[LOCALE]??v[CONFIG.client.language]??v.en??'';return v??''}
function t(k){return I18N[LOCALE][k]??I18N.en[k]??k}
function message(s){const m=MESSAGES[s];return m?m[LOCALES.indexOf(LOCALE)]:s}
function localizeData(value,key=''){if(Array.isArray(value))return value.map(x=>localizeData(x));if(value&&typeof value==='object'){if(LOCALES.some(l=>l in value))return loc(value);return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,localizeData(v,k)]))}if(typeof value==='string'&&!['id','q','type','time','date','dates'].includes(key))return message(value);return value}
function dateRange(){const fmt=new Intl.DateTimeFormat(LOCALE,{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'});return fmt.format(new Date(CONFIG.trip.startDate+'T12:00:00Z'))+' – '+fmt.format(new Date(CONFIG.trip.endDate+'T12:00:00Z'))}
function typeLabel(type){return t(({'הכל':'all','מסעדה':'restaurant','יקב':'winery','טבע':'nature','חיי לילה':'nightlife','קניות':'shopping'})[type]||type)}
function emptyCard(text){return `<div class="card empty-state"><span>◇</span><p>${escapeHtml(text)}</p></div>`}
function languageSelect(id){return `<select class="language-select" id="${id}" aria-label="${t('language')}" onchange="setLocale(this.value)">${LOCALES.map(l=>`<option value="${l}" ${l===LOCALE?'selected':''}>${({he:'עברית',en:'English',ru:'Русский',ar:'العربية'})[l]}</option>`).join('')}</select>`}
function updateChrome(){document.querySelectorAll('.start-arrow').forEach(n=>{n.textContent=['he','ar'].includes(LOCALE)?'←':'→'});document.documentElement.lang=LOCALE;document.documentElement.dir=['he','ar'].includes(LOCALE)?'rtl':'ltr';document.title='NAVIGAM · '+loc(CONFIG.trip.title);document.querySelectorAll('[data-i18n]').forEach(n=>{n.textContent=t(n.dataset.i18n)});document.getElementById('welcomeTrip').textContent=loc(CONFIG.trip.title);document.getElementById('welcomeLanguage').innerHTML=languageSelect('entryLanguage');document.querySelectorAll('.appbar .side')[0].setAttribute('aria-label',t('profile'));document.querySelectorAll('.appbar .side')[1].setAttribute('aria-label',t('home'));document.querySelector('.bottom').setAttribute('aria-label',t('navigate'))}
function setLocale(locale){if(!LOCALES.includes(locale))return;closeSheet();LOCALE=locale;DATA=localizeData(CONFIG.data);S.transSrc=locale;S.transDst=CONFIG.destination.language===locale?'en':CONFIG.destination.language;translationLanguage=S.transDst;translationDraft='';translationOutput='';translationValid=false;chatHistory.length=0;saveValue('language',locale);updateChrome();render()}
const PHRASES={he:'שלום, יש לנו הזמנה לשניים. אפשר בבקשה עזרה?',en:'Hello, we have a reservation for two. Could you please help us?',ru:'Здравствуйте, у нас бронь на двоих. Не могли бы вы помочь?',ar:'مرحباً، لدينا حجز لشخصين. هل يمكنك مساعدتنا من فضلك؟',sq:'Përshëndetje, kemi një rezervim për dy persona. A mund të na ndihmoni, ju lutem?',el:'Γεια σας, έχουμε κράτηση για δύο άτομα. Μπορείτε να μας βοηθήσετε;',it:'Buongiorno, abbiamo una prenotazione per due. Può aiutarci, per favore?',fr:'Bonjour, nous avons une réservation pour deux. Pouvez-vous nous aider ?',es:'Hola, tenemos una reserva para dos. ¿Puede ayudarnos, por favor?'};

let sessionExchange=null;

const tripStorage={getItem:k=>localStorage.getItem(storageKey(k)),setItem:(k,v)=>localStorage.setItem(storageKey(k),v)};

/* WORK NEXT: incremental QA fixes; original trip data retained. */
function readSaved(key,fallback,valid){try{const raw=tripStorage.getItem(key);if(raw===null)return fallback;const value=JSON.parse(raw);return valid(value)?value:fallback}catch(e){return fallback}}
function saveValue(key,value){try{tripStorage.setItem(key,JSON.stringify(value));return true}catch(e){toast('השינוי נשמר להפעלה זו בלבד; אחסון הדפדפן אינו זמין.');return false}}
let DATA=localizeData(CONFIG.data);
const HERO=CONFIG.images.hero;
const IMG=CONFIG.images;
const S={route:'home',day:readSaved('selected_day',0,x=>Number.isInteger(x)&&x>=0&&x<DATA.tripDays.length),placeFilter:'all',favorites:new Set(readSaved('nav_favs',[],Array.isArray)),check:readSaved('nav_check',{},x=>x && typeof x==='object' && !Array.isArray(x)),offline:false,transSrc:LOCALE,transDst:CONFIG.destination.language===LOCALE?'en':CONFIG.destination.language,live:false};
const langNames={he:'עברית',sq:'אלבנית',el:'יוונית',en:'אנגלית',ar:'ערבית',ru:'רוסית',it:'איטלקית'};
const speechLocale={he:'he-IL',sq:'sq-AL',el:'el-GR',en:'en-US',ar:'ar-SA',ru:'ru-RU',it:'it-IT',fr:'fr-FR',es:'es-ES'};
function enterApp(){document.getElementById('splash').classList.remove('active');document.getElementById('live').classList.add('active');render()}
function goSplash(){document.getElementById('live').classList.remove('active');document.getElementById('splash').classList.add('active')}
function route(r){S.route=r;document.querySelectorAll('.nav[data-route]').forEach(n=>n.classList.toggle('active',n.dataset.route===r));render()}
function render(){if(!window.NAVIGAM_CONFIG)return;stopMap();if(DATA.tripDays[S.day]?.locked)S.day=0;let m=document.getElementById('main');m.scrollTop=0;({home:renderHome,itinerary:renderItinerary,map:renderMap,favorites:renderFavorites,places:renderPlaces,trending:renderTrending,hotels:renderHotels,info:renderInfo,weather:renderWeather,currency:renderCurrency,checklist:renderChecklist,offline:renderOffline,profile:renderProfile,support:renderSupport}[S.route]||renderHome)(m)}
function renderHome(m){const d=DATA.tripDays[S.day],first=d.items[0];m.innerHTML=`<div class="home-hero premium"><img src="${escapeHtml(HERO)}" onerror="imageFailed(this)" alt="${escapeHtml(loc(CONFIG.destination.name))}"><div class="home-copy"><div class="eyebrow">NAVIGAM · ${escapeHtml(loc(CONFIG.destination.name))}</div><h1>${escapeHtml(loc(CONFIG.trip.title))}</h1><p>${dateRange()} · ${DATA.tripDays.length} ${t('days')} · ${escapeHtml(loc(CONFIG.client.party))}</p></div></div><div class="card next-card"><div class="section-head"><h2>${t('selectedDay')}</h2><span>${t('day')} ${S.day+1} · ${d.date}</span></div><div class="next-row"><div class="timebox">${escapeHtml(first.time)}</div><div><strong>${escapeHtml(first.title)}</strong><small>${escapeHtml(first.sub)}</small></div><button class="btn ghost compact" onclick="route('itinerary')">${t('viewDay')}</button></div></div><div class="quick premium-quick">${[['itinerary','🗓'],['map','⌖'],['places','♧'],['trending','🔥'],['hotels','⌂'],['offline','↓']].map(([r,icon],i)=>`<button class="qbtn q${i+1}" onclick="${r==='nightlife'?'openNightlife()':`route('${r}')`}"><i>${icon}</i><span>${t(r)}</span></button>`).join('')}</div><div class="card translate-card premium-card"><div class="translate-icon">◎</div><div><h3>${t('translate')}</h3><p>${escapeHtml(translationLanguageName(LOCALE))} ⇄ ${escapeHtml(translationLanguageName(CONFIG.destination.language))}</p></div><button class="btn primary compact" onclick="openAvia('translate')">${t('openTranslate')}</button></div>`}
function renderItinerary(m){const d=DATA.tripDays[S.day];m.innerHTML=`<div class="screen-title">${t('itinerary')}</div><div class="trip-head"><div class="topline"><div><h2>${escapeHtml(loc(CONFIG.destination.name))}</h2><p>${dateRange()}</p></div><span class="tag">${S.day+1} / ${DATA.tripDays.length}</span></div><div class="trip-cover"><img src="${escapeHtml(IMG.itinerary)}" onerror="imageFailed(this)" alt="${escapeHtml(loc(CONFIG.destination.name))}"></div></div>${dayTabs(false)}<div class="day-heading"><h3>${escapeHtml(d.title)}</h3><span>${d.date}</span></div>${d.summary?`<p class="route-note">${escapeHtml(d.summary)}</p>`:''}<div class="timeline">${d.items.map((e,i)=>`<div class="event"><div class="event-time">${e.time}</div><div class="dot"></div><div class="event-body"><strong>${escapeHtml(e.title)}</strong><small>${escapeHtml(e.sub)}</small></div><div class="stop-nav">${e.navigationResolved?`<button class="navmini" aria-label="Google Maps ${i+1}" onclick="maps('${jsq(e.q)}')">G</button><button class="navmini" aria-label="Waze ${i+1}" onclick="waze('${jsq(e.q)}')">W</button>`:`<span class="route-note">${t('locationPending')}</span>`}</div></div>`).join('')}</div>`}
function placeHtml(p){const saved=S.favorites.has(p.id),url=IMG.places[p.id];return `<div class="card place" data-place-id="${escapeHtml(p.id)}"><div class="place-thumb">${url?`<img src="${escapeHtml(url)}" alt="${escapeHtml(p.name)}" loading="lazy" onerror="imageFailed(this)">`:`<div class="image-placeholder" role="img" aria-label="${escapeHtml(p.name)}"><span>◇</span><small>${escapeHtml(p.name)}</small></div>`}</div><div><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.area)} · ${typeLabel(p.type)}</p><p>${escapeHtml(p.tag)}</p>${photoNote(CONFIG.imagePresentation?.places?.[p.id])}${navButtons(p.q)}</div><button class="heart ${saved?'saved':''}" aria-label="${t('savePlace')}" aria-pressed="${saved}" onclick="toggleFav('${jsq(p.id)}')">${saved?'♥':'♡'}</button></div>`}

function openNightlife(){S.placeFilter='nightlife';route('places')}
function renderPlaces(m){const types=['all','restaurant','shopping','attractions','nature','family','nightlife'],list=DATA.places.filter(p=>S.placeFilter==='all'||p.type===S.placeFilter||(S.placeFilter==='family'&&p.familyFriendly));m.innerHTML=`<div class="screen-title">${t('places')}</div><div class="tabs">${types.map(v=>`<button class="tab ${v===S.placeFilter?'active':''}" onclick="S.placeFilter='${v}';render()">${typeLabel(v)}</button>`).join('')}</div><div class="cards">${list.map(placeHtml).join('')||emptyCard(t('noPlaces'))}</div>`}
function platformName(p){return ({tiktok:'TikTok',instagram:'Instagram',facebook:'Facebook'})[p]||p}
function trendCard(item){
  const badges=(item.platforms||[]).map(p=>`<span class="trend-badge ${escapeHtml(p)}">${escapeHtml(platformName(p))}</span>`).join('');
  const sources=(item.socialSources||[]).map(s=>`<a class="trend-source" href="${escapeHtml(s.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(platformName(s.platform))}</a>`).join('');
  return `<article class="card trend-card"><div class="trend-head"><div><span class="trend-kicker">🔥 ${t('trendingNow')}</span><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.area||item.category)}</p></div><div class="trend-badges">${badges}</div></div><p class="trend-desc">${escapeHtml(item.description)}</p><div class="trend-why"><strong>${t('whyTrending')}</strong><p>${escapeHtml(item.whyTrending)}</p></div><div class="trend-why match"><strong>${t('whyForYou')}</strong><p>${escapeHtml(item.whyMatch)}</p></div><div class="trend-footer"><div class="trend-sources"><span>${t('socialSignals')}</span>${sources}</div>${navButtons(item.q)}</div></article>`;
}
function renderTrending(m){
  const list=Array.isArray(DATA.trends)?DATA.trends:[];
  m.innerHTML=`<div class="screen-title">${t('trending')}</div><p class="screen-sub trend-intro">${t('trendingIntro')}</p><div class="cards trend-list">${list.map(trendCard).join('')||emptyCard(t('noTrending'))}</div><p class="trend-disclaimer">${t('trendDisclaimer')}</p>`;
}



function renderFavorites(m){const list=DATA.places.filter(p=>S.favorites.has(p.id));m.innerHTML=`<div class="screen-title">${t('favorites')}</div><div class="cards">${list.map(p=>`<div class="card saved-place"><div><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.area)} · ${typeLabel(p.type)}</p>${navButtons(p.q)}</div><button class="heart saved" aria-label="${t('savePlace')}" onclick="toggleFav('${jsq(p.id)}')">♥</button></div>`).join('')||emptyCard(t('savedEmpty'))}</div>`}
function renderHotels(m){m.innerHTML=`<div class="screen-title">${t('hotels')}</div><p class="screen-sub">${dateRange()}</p><div class="cards two">${DATA.hotels.map((h,i)=>`<article class="card hotel-card"><div class="hotel-img"><img src="${escapeHtml(IMG.hotels[h.id])}" onerror="imageFailed(this)" alt="${escapeHtml(h.name)}"></div><div class="hotel-body"><span class="tag">${escapeHtml(h.dates)}</span><h3>${escapeHtml(h.name)}</h3><p>${escapeHtml(h.city)} · ${escapeHtml(h.note)}</p>${photoNote(CONFIG.imagePresentation?.hotels?.[h.id])}${navButtons(h.q)}</div></article>`).join('')||emptyCard(t('noHotels'))}</div>`}
function renderInfo(m){m.innerHTML=`<div class="screen-title">${t('info')}</div><div class="card info-list">${[['weather','☀'],['currency','€'],['map','⌖'],['trending','🔥'],['offline','↓'],['checklist','☑'],['support','?']].map(([r,icon])=>`<button class="info-row row-button" onclick="route('${r}')"><span class="info-ico">${icon}</span><strong>${t(r)}</strong><span class="chev">›</span></button>`).join('')}<button class="info-row row-button" onclick="openAvia('translate')"><span class="info-ico">◎</span><strong>${t('translate')}</strong><span class="chev">›</span></button></div>`}
function infoAction(i){if(i===0)return route('weather');if(i===1)return route('currency');if(i===5)return openAvia('translate');toast(DATA.info[i][1])}
function renderProfile(m){m.innerHTML=`<div class="screen-title">${t('profile')}</div><div class="profile-head"><div class="avatar">◎</div><div><h2>${escapeHtml(loc(CONFIG.client.name))}</h2><p>${escapeHtml(loc(CONFIG.trip.title))}</p></div></div><div class="card">${[['itinerary','myTrips'],['favorites','favorites'],['trending','trending'],['info','info'],['checklist','checklist'],['offline','offline'],['support','support']].map(([r,label])=>`<button class="setting row-button" onclick="route('${r}')"><span>${t(label)}</span><span>›</span></button>`).join('')}<div class="setting language-setting"><label for="profileLanguage">${t('language')}</label>${languageSelect('profileLanguage')}</div></div>`}
function openProfile(){route('profile')}
function toggleFav(id){S.favorites.has(id)?S.favorites.delete(id):S.favorites.add(id);saveValue('nav_favs',[...S.favorites]);toast(S.favorites.has(id)?'נשמר במועדפים':'הוסר מהמועדפים');render()}
function jsq(s){return escapeHtml(JSON.stringify(String(s)).slice(1,-1).replace(/'/g,"\\'"))}

let leafletPromise=null;
function openSheet(html){if(!document.getElementById('sheetback').classList.contains('show'))sheetFocus=document.activeElement;document.getElementById('sheet').innerHTML=html;document.getElementById('sheetback').classList.add('show');document.getElementById('live').inert=true;document.querySelector('#sheet button')?.focus()}
function closeSheet(){captureTranslation();stopVoice();translationRequest++;document.getElementById('sheetback').classList.remove('show');document.getElementById('live').inert=false;sheetFocus?.focus()}
function openAvia(tab='chat'){captureTranslation();stopVoice();translationRequest++;openSheet(`<div class="sheethead"><div><h2>${t('avia')}</h2><small>${t('aviaTag')}</small></div><button aria-label="${t('close')}" onclick="closeSheet()">✕</button></div><div class="tabs"><button class="tab ${tab==='chat'?'active':''}" onclick="openAvia('chat')">${t('chat')}</button><button class="tab ${tab==='translate'?'active':''}" onclick="openAvia('translate')">${t('translate')}</button></div>${tab==='chat'?aviaChat():aviaTranslate()}`);if(tab==='translate'){const input=document.getElementById('trIn'),output=document.getElementById('trOut');if(input)input.value=translationDraft;if(output)output.textContent=translationOutput||t('output')}}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(msg){let t=document.getElementById('toast');t.textContent=message(msg);t.classList.add('show');clearTimeout(window.__to);window.__to=setTimeout(()=>t.classList.remove('show'),2500)}
let mapGeneration=0,activeMap=null,sheetFocus=null,translationRequest=0,translationDraft='',translationOutput='',translationLanguage=CONFIG.destination.language,translationValid=false,recognition=null,voiceGeneration=0,voiceTimer=null;
const roadCache=new Map(),chatHistory=[];
function stopMap(){mapGeneration++;if(activeMap){activeMap.remove();activeMap=null}}
async function fetchJSON(url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const response=await fetch(url,{signal:controller.signal});if(!response.ok)throw Error('HTTP '+response.status);return await response.json()}finally{clearTimeout(timer)}}
function openNavigation(q){openSheet(`<div class="sheethead"><h2>${t('navigate')}</h2><button aria-label="${t('close')}" onclick="closeSheet()">✕</button></div><p dir="auto">${escapeHtml(q)}</p>${navButtons(q)}`)}
function captureTranslation(){const input=document.getElementById('trIn');if(input)translationDraft=input.value}
function updateLiveToggle(){const button=document.getElementById('liveToggle');if(button){button.classList.toggle('on',S.live);button.setAttribute('aria-checked',String(S.live))}}
function stopVoice(){voiceGeneration++;clearTimeout(voiceTimer);S.live=false;if(recognition){const old=recognition;recognition=null;old.abort()}if('speechSynthesis'in window)speechSynthesis.cancel();updateLiveToggle()}
function toggleLive(){if(S.live){stopVoice();return}S.live=true;updateLiveToggle();recognize('src')}
document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeSheet();return}if((event.key==='Enter'||event.key===' ')&&event.target.matches?.('[role="button"][tabindex]')){event.preventDefault();event.target.click()}if(event.key==='Tab'&&document.getElementById('sheetback').classList.contains('show')){const controls=[...document.getElementById('sheet').querySelectorAll('button,input,textarea,select,a[href]')].filter(x=>!x.disabled),first=controls[0],last=controls[controls.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopVoice()});

function dayTabs(map){return `<div class="${map?'map-daytabs':'daytabs'}">${DATA.tripDays.map((d,i)=>`<button class="${map?'map-daytab':'daytab'} ${i===S.day?'active':''}" aria-pressed="${i===S.day}" onclick="selectDay(${i})">${d.locked?'🔒 ':''}${t('day')} ${i+1}</button>`).join('')}</div>`}
function navButtons(q){return `<div class="place-actions"><button class="btn ghost" onclick="maps('${jsq(q)}')">Google Maps</button><button class="btn soft" onclick="waze('${jsq(q)}')">Waze</button></div>`}
function renderSupport(m){m.innerHTML=`<div class="screen-title">${t('support')}</div><div class="card support-card"><span class="support-icon">◉</span><h2>${t('helpTitle')}</h2><p>${t('helpText')}</p><button class="btn primary full" onclick="openAvia('chat')">${t('ask')}</button>${CONFIG.support?.email?`<a class="btn ghost full" href="mailto:${escapeHtml(CONFIG.support.email)}">${t('email')}</a>`:''}</div>`}
function answerAvia(intent){appendChat(t(intent),aviaAnswer(intent))}
function appendChat(q,a){chatHistory.push({me:true,text:q},{me:false,text:a});const c=document.getElementById('chat');c.insertAdjacentHTML('beforeend',`<div class="bubble me">${escapeHtml(q)}</div><div class="bubble">${escapeHtml(a).replace(/\n/g,'<br>')}</div>`);c.scrollTop=c.scrollHeight}
function selectDay(day){if(!Number.isInteger(day)||day<0||day>=DATA.tripDays.length)return;if(DATA.tripDays[day].locked){openLockedDay(day);return;}S.day=day;saveValue('selected_day',day);render()}
function translationInputChanged(){translationRequest++;stopVoice();translationDraft=document.getElementById('trIn')?.value||'';translationOutput='';translationValid=false;const out=document.getElementById('trOut');if(out)out.textContent=t('output')}
function photoNote(meta){return meta?.kind==='atmosphere'?`<p class="photo-note">${t('photoAtmosphere')}</p>`:''}


function openLockedDay(day){openSheet(`<div class="sheethead"><h2>🔒 ${t('day')} ${day+1}</h2><button onclick="closeSheet()" aria-label="${t('close')}">✕</button></div><div class="card support-card"><h2>${t('lockedTitle')}</h2><p>${t('lockedBody')}</p><p>${t('pricing')}</p><button class="btn primary full" onclick="openAvia('chat')">${t('ask')}</button></div>`)}
function imageFailed(img){const box=img.parentElement;img.remove();box.classList.add('image-unavailable');const placeholder=document.createElement('span');placeholder.className='image-placeholder';placeholder.textContent=img.alt||t('photos');box.prepend(placeholder);}
