import { createClient } from "npm:@supabase/supabase-js@2.57.4";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!; const SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!; const supabase=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const allowedOrigins=new Set(["https://triply-triply2.vercel.app","https://triply-swart-seven.vercel.app","https://mytriply.co.il","https://www.mytriply.co.il"]);
function cors(origin:string|null){const o=origin&&allowedOrigins.has(origin)?origin:"https://mytriply.co.il";return {"Access-Control-Allow-Origin":o,"Vary":"Origin","Access-Control-Allow-Headers":"content-type, apikey, authorization","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store, private","X-Content-Type-Options":"nosniff","Referrer-Policy":"no-referrer"}}
function json(body:unknown,status=200,origin:string|null=null){return new Response(JSON.stringify(body),{status,headers:cors(origin)})}
async function sha256(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function pick(p:any,keys:string[]){const out:any={};for(const k of keys)if(p?.[k]!==undefined&&p?.[k]!=="")out[k]=p[k];return out}
const hotelKeys=["hotel_status","hotels","hotel_route_known","hotel_bases","hotel_budget_night","hotel_level","hotel_location","hotel_features","hotel_min_rating","hotel_cancellation","hotel_breakfast","hotel_parking","hotel_style_notes","hotel_search_permission"];
const flightKeys=["flight_status","flights","flight_airline","flight_number","flight_origin","flight_destination_airport","flight_outbound_date","flight_outbound_time","flight_return_date","flight_return_time","flight_lookup_permission","flight_search_permission","flight_origin_preference","flight_destination_preference","flight_outbound_window","flight_return_window","flight_date_flexibility","flight_stops","flight_baggage","flight_fare_flexibility","flight_airlines_preferred","flight_airlines_avoid","flight_airports_preferred","flight_budget","flight_priority"];
Deno.serve(async(req:Request)=>{
 const origin=req.headers.get("origin"); if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(origin)}); if(req.method!=="POST")return json({ok:false,error:"method_not_allowed"},405,origin); if(origin&&!allowedOrigins.has(origin))return json({ok:false,error:"origin_not_allowed"},403,origin);
 try{
  const body=await req.json(); if(body?.website||body?.company_site)return json({ok:true,ignored:true},200,origin);
  const submissionId=String(body?.submission_id||"").trim(),customer=body?.customer||{},trip=body?.trip||{}; if(submissionId.length<8)return json({ok:false,error:"invalid_submission_id"},400,origin); if(!String(customer.customer_name||"").trim())return json({ok:false,error:"missing_customer_name"},400,origin); if(!String(trip.destination||"").trim())return json({ok:false,error:"missing_destination"},400,origin); if(!String(trip.start_date||"").trim()||!String(trip.end_date||"").trim())return json({ok:false,error:"missing_dates"},400,origin);
  const ip=req.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||req.headers.get("cf-connecting-ip")||"unknown"; const ipHash=await sha256(ip+"|triply-v31"); const oneHourAgo=new Date(Date.now()-3600_000).toISOString(); const {count}=await supabase.from("triply_intake_requests").select("id",{count:"exact",head:true}).eq("ip_hash",ipHash).gte("created_at",oneHourAgo); if((count||0)>=20)return json({ok:false,error:"rate_limited"},429,origin); await supabase.from("triply_intake_requests").insert({ip_hash:ipHash,submission_id:submissionId});
  const {data:created,error:createErr}=await supabase.rpc("triply_intake_create",{p_submission_id:submissionId,p_customer:customer,p_trip:trip}); if(createErr)throw createErr; const tripCode=created.trip_code as string,tripId=created.trip_id as string,prefs=trip?.preferences||{};
  let hotelMatchRequested=false; const hotelStatus=String(prefs.hotel_status||""),hotelPermission=String(prefs.hotel_search_permission||""); if(!created.duplicate&&hotelPermission.startsWith("כן")&&hotelStatus!=="כל המלונות כבר סגורים"){const scope=hotelStatus.includes("חלק")?"fill_unbooked_nights":"route_bases_and_hotels";const {error}=await supabase.from("hotel_search_requests").upsert({trip_id:tripId,request_key:"intake-primary",scope,city:null,country:String(trip.destination||""),check_in:String(trip.start_date||"")||null,check_out:String(trip.end_date||"")||null,status:"pending",source:"questionnaire_autopilot",preferences:{...pick(prefs,hotelKeys),destination:trip.destination,party_type:trip.party_type,travel_dna:trip.travel_dna}},{onConflict:"trip_id,request_key"});if(error)console.error("hotel request",error);else hotelMatchRequested=true;}
  let flightMatchRequested=false; const flightStatus=String(prefs.flight_status||""),flightLookup=String(prefs.flight_lookup_permission||""),flightPermission=String(prefs.flight_search_permission||""); const wantsIdentify=flightLookup.startsWith("כן")&&flightStatus&&flightStatus!=="עדיין אין טיסות"; const wantsSearch=flightPermission.startsWith("כן")&&flightStatus!=="הלוך וחזור כבר סגורים"; if(!created.duplicate&&(wantsIdentify||wantsSearch)){let scope="roundtrip_search";if(wantsIdentify&&!wantsSearch)scope="identify_booking";else if(flightStatus.includes("רק הלוך")||flightStatus.includes("רק חזור")||flightStatus.includes("חלק"))scope="fill_missing_leg";const {error}=await supabase.from("flight_search_requests").upsert({trip_id:tripId,request_key:"intake-primary",scope,origin:String(prefs.flight_origin_preference||prefs.flight_origin||"")||null,destination:String(prefs.flight_destination_preference||trip.destination||"")||null,outbound_date:String(prefs.flight_outbound_date||trip.start_date||"")||null,return_date:String(prefs.flight_return_date||trip.end_date||"")||null,status:"pending",source:"questionnaire_autopilot",preferences:{...pick(prefs,flightKeys),destination:trip.destination,party_type:trip.party_type,travelers:prefs.travelers||trip.travelers,travel_dna:trip.travel_dna}},{onConflict:"trip_id,request_key"});if(error)console.error("flight request",error);else flightMatchRequested=true;}
  const attachments=Array.isArray(body?.attachments)?body.attachments:[]; const skippedDocuments=attachments.slice(0,30).map((a:any)=>({name:String(a?.name||"file"),reason:"source_document_not_persisted_use_transient_extraction"}));
  // The database trigger creates the job; the scheduled dispatcher owns execution.
  // Never bypass that workflow with a fire-and-forget service-key request.
  const {data:job,error:jobError}=await supabase.from("triply_autopilot_jobs").select("status").eq("trip_id",tripId).maybeSingle();
  const autopilotStatus=jobError?"unknown":job?.status||"missing";
  const autopilotQueued=autopilotStatus==="queued";

  await supabase.from("security_audit_events").insert({event_type:"public_intake_received",trip_id:tripId,target_type:"trip",target_id:tripId,metadata:{attachments_received:attachments.length,attachments_persisted:0}});
  return json({ok:true,trip_code:tripCode,trip_id:tripId,duplicate:!!created.duplicate,hotel_match_requested:hotelMatchRequested,flight_match_requested:flightMatchRequested,autopilot_queued:autopilotQueued,autopilot_status:autopilotStatus,uploaded_documents:0,skipped_documents:skippedDocuments,document_policy:"original_files_are_not_persisted"},200,origin);
 }catch(e){console.error("triply-intake",e);return json({ok:false,error:"intake_failed"},500,origin)}
});
